public class WS_InformeNegociaciones {
    public class GetAccesoriosDespachados {
        public String arg0;
        public String arg1;
        public String arg2;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2'};
    }
    public class GetAccesoriosSolicitados {
        public String arg0;
        public String arg1;
        public String arg2;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2'};
    }
    public class GetAccesoriosDisponibles {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3'};
    }
    public class GetExchangeRateByDate {
        public String arg0;
        public String arg1;
        public String arg2;
        public DateTime arg3;
        public String arg4;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg4_type_info = new String[]{'arg4','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3','arg4'};
    }
    public class GetExchangeRateByDateResponse {
        public Decimal return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetAccesoriosEstadoDisponibilidadResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetVehiculoByChasisResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class InsertarObjetoResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class EliminarSolicitud {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3'};
    }
    public class GetAllRecibosDia {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        public String arg4;
        public String arg5;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg4_type_info = new String[]{'arg4','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg5_type_info = new String[]{'arg5','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3','arg4','arg5'};
    }

    public class GetAccesoriosChasisResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetAccesoriosChasis {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3'};
    }
    public class GetAccesoriosDespachadosResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetAccesoriosSolicitadosResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetAllRecibosDiaResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetVehiculoByShortNumber {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3'};
    }
    public class EliminarSolicitudResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetVehiculoByShortNumberResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetAccesoriosEstadoDisponibilidad {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3'};
    }
    public class InsertarObjeto {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        public Integer arg4;
        public Integer arg5;
        public Integer arg6;
        public String arg7;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg4_type_info = new String[]{'arg4','http://ws.salesforce.casapellas.com/',null,'1','1','false'};
        private String[] arg5_type_info = new String[]{'arg5','http://ws.salesforce.casapellas.com/',null,'1','1','false'};
        private String[] arg6_type_info = new String[]{'arg6','http://ws.salesforce.casapellas.com/',null,'1','1','false'};
        private String[] arg7_type_info = new String[]{'arg7','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3','arg4','arg5','arg6','arg7'};
    }
    public class GetAccesoriosDisponiblesResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class GetVehiculoByChasis {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        private String[] arg0_type_info = new String[]{'arg0','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://ws.salesforce.casapellas.com/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://ws.salesforce.casapellas.com/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3'};
    }
    public class wsInformeNegociacionPort {
		public String endpoint_x = Label.URL_WS_InformeNegociacion;                                    
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x;
        private String[] ns_map_type_info = new String[]{'http://ws.salesforce.casapellas.com/', 'WS_InformeNegociaciones'};

        public String GetVehiculoByChasis(String arg0,String arg1,String arg2,String arg3) {
            WS_InformeNegociaciones.GetVehiculoByChasis request_x = new WS_InformeNegociaciones.GetVehiculoByChasis();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            WS_InformeNegociaciones.GetVehiculoByChasisResponse response_x;
            Map<String, WS_InformeNegociaciones.GetVehiculoByChasisResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetVehiculoByChasisResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetVehiculoByChasis',
              'http://ws.salesforce.casapellas.com/',
              'GetVehiculoByChasisResponse',
              'WS_InformeNegociaciones.GetVehiculoByChasisResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        
        public String GetAccesoriosChasis(String arg0,String arg1,String arg2,String arg3) {
            WS_InformeNegociaciones.GetAccesoriosChasis request_x = new WS_InformeNegociaciones.GetAccesoriosChasis();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            WS_InformeNegociaciones.GetAccesoriosChasisResponse response_x;
            Map<String, WS_InformeNegociaciones.GetAccesoriosChasisResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetAccesoriosChasisResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosChasis',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosChasisResponse',
              'WS_InformeNegociaciones.GetAccesoriosChasisResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        
        public String InsertarObjeto(String arg0,String arg1,String arg2,String arg3,Integer arg4,Integer arg5,Integer arg6,String arg7) {
            WS_InformeNegociaciones.InsertarObjeto request_x = new WS_InformeNegociaciones.InsertarObjeto();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            request_x.arg4 = arg4;
            request_x.arg5 = arg5;
            request_x.arg6 = arg6;
            request_x.arg7 = arg7;
            WS_InformeNegociaciones.InsertarObjetoResponse response_x;
            Map<String, WS_InformeNegociaciones.InsertarObjetoResponse> response_map_x = new Map<String, WS_InformeNegociaciones.InsertarObjetoResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'InsertarObjeto',
              'http://ws.salesforce.casapellas.com/',
              'InsertarObjetoResponse',
              'WS_InformeNegociaciones.InsertarObjetoResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String GetAllRecibosDia(String arg0,String arg1,String arg2,String arg3,String arg4,String arg5) {
            WS_InformeNegociaciones.GetAllRecibosDia request_x = new WS_InformeNegociaciones.GetAllRecibosDia();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            request_x.arg4 = arg4;
            request_x.arg5 = arg5;
            WS_InformeNegociaciones.GetAllRecibosDiaResponse response_x;
            Map<String, WS_InformeNegociaciones.GetAllRecibosDiaResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetAllRecibosDiaResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetAllRecibosDia',
              'http://ws.salesforce.casapellas.com/',
              'GetAllRecibosDiaResponse',
              'WS_InformeNegociaciones.GetAllRecibosDiaResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String GetAccesoriosEstadoDisponibilidad(String arg0,String arg1,String arg2,String arg3) {
            WS_InformeNegociaciones.GetAccesoriosEstadoDisponibilidad request_x = new WS_InformeNegociaciones.GetAccesoriosEstadoDisponibilidad();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            WS_InformeNegociaciones.GetAccesoriosEstadoDisponibilidadResponse response_x;
            Map<String, WS_InformeNegociaciones.GetAccesoriosEstadoDisponibilidadResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetAccesoriosEstadoDisponibilidadResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosEstadoDisponibilidad',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosEstadoDisponibilidadResponse',
              'WS_InformeNegociaciones.GetAccesoriosEstadoDisponibilidadResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String EliminarSolicitud(String arg0,String arg1,String arg2,String arg3) {
            WS_InformeNegociaciones.EliminarSolicitud request_x = new WS_InformeNegociaciones.EliminarSolicitud();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            WS_InformeNegociaciones.EliminarSolicitudResponse response_x;
            Map<String, WS_InformeNegociaciones.EliminarSolicitudResponse> response_map_x = new Map<String, WS_InformeNegociaciones.EliminarSolicitudResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'EliminarSolicitud',
              'http://ws.salesforce.casapellas.com/',
              'EliminarSolicitudResponse',
              'WS_InformeNegociaciones.EliminarSolicitudResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String GetVehiculoByShortNumber(String arg0,String arg1,String arg2,String arg3) {
            WS_InformeNegociaciones.GetVehiculoByShortNumber request_x = new WS_InformeNegociaciones.GetVehiculoByShortNumber();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            WS_InformeNegociaciones.GetVehiculoByShortNumberResponse response_x;
            Map<String, WS_InformeNegociaciones.GetVehiculoByShortNumberResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetVehiculoByShortNumberResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetVehiculoByShortNumber',
              'http://ws.salesforce.casapellas.com/',
              'GetVehiculoByShortNumberResponse',
              'WS_InformeNegociaciones.GetVehiculoByShortNumberResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }

        public Decimal GetExchangeRateByDate(String arg0,String arg1,String arg2,DateTime arg3,String arg4) {
            WS_InformeNegociaciones.GetExchangeRateByDate request_x = new WS_InformeNegociaciones.GetExchangeRateByDate();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            request_x.arg4 = arg4;
            WS_InformeNegociaciones.GetExchangeRateByDateResponse response_x;
            Map<String, WS_InformeNegociaciones.GetExchangeRateByDateResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetExchangeRateByDateResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetExchangeRateByDate',
              'http://ws.salesforce.casapellas.com/',
              'GetExchangeRateByDateResponse',
              'WS_InformeNegociaciones.GetExchangeRateByDateResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String GetAccesoriosDisponibles(String arg0,String arg1,String arg2,String arg3) {
            WS_InformeNegociaciones.GetAccesoriosDisponibles request_x = new WS_InformeNegociaciones.GetAccesoriosDisponibles();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            WS_InformeNegociaciones.GetAccesoriosDisponiblesResponse response_x;
            Map<String, WS_InformeNegociaciones.GetAccesoriosDisponiblesResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetAccesoriosDisponiblesResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosDisponibles',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosDisponiblesResponse',
              'WS_InformeNegociaciones.GetAccesoriosDisponiblesResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String GetAccesoriosDespachados(String arg0,String arg1,String arg2) {
            WS_InformeNegociaciones.GetAccesoriosDespachados request_x = new WS_InformeNegociaciones.GetAccesoriosDespachados();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            WS_InformeNegociaciones.GetAccesoriosDespachadosResponse response_x;
            Map<String, WS_InformeNegociaciones.GetAccesoriosDespachadosResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetAccesoriosDespachadosResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosDespachados',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosDespachadosResponse',
              'WS_InformeNegociaciones.GetAccesoriosDespachadosResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String GetAccesoriosSolicitados(String arg0,String arg1,String arg2) {
            WS_InformeNegociaciones.GetAccesoriosSolicitados request_x = new WS_InformeNegociaciones.GetAccesoriosSolicitados();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            WS_InformeNegociaciones.GetAccesoriosSolicitadosResponse response_x;
            Map<String, WS_InformeNegociaciones.GetAccesoriosSolicitadosResponse> response_map_x = new Map<String, WS_InformeNegociaciones.GetAccesoriosSolicitadosResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosSolicitados',
              'http://ws.salesforce.casapellas.com/',
              'GetAccesoriosSolicitadosResponse',
              'WS_InformeNegociaciones.GetAccesoriosSolicitadosResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
    }
}